#!/usr/bin/env bash

echo "Installing noizwaves dotfiles"

if [[ "$(hostname)" =~ 'odroid' ]]; then
  ./install-server.sh
elif [[ $OSTYPE == 'darwin'* ]]; then
  ./install-macos.sh
elif [[ "$REMOTE_CONTAINERS" == 'true' ]] || test -f "/.dockerenv"; then
  ./install-devcontainers.sh
elif command -v pacman &>/dev/null; then
  ./install-arch.sh
else
  ./install-ubuntu.sh
fi
