binaries:
    - name: delta
      version: 0.16.5
      source:
        org: dandavison
        repo: delta
        releaseName: '{{ .Version }}'
        releaseRegex: \d+\.\d+\.\d+
        fileName: delta-{{ .Version }}-{{ .Arch }}-{{ .Platform }}.{{ .Ext }}
        overrides:
            darwin:
                amd64:
                    - apple-darwin
                    - x86_64
                    - tar.gz
                arm64:
                    - apple-darwin
                    - aarch64
                    - tar.gz
            linux:
                amd64:
                    - unknown-linux-gnu
                    - x86_64
                    - tar.gz
                arm64:
                    - unknown-linux-gnu
                    - aarch64
                    - tar.gz
        versionFlags:
            - --version
        versionRegex: \d+\.\d+\.\d+
    - name: direnv
      version: 2.33.0
      source:
        org: direnv
        repo: direnv
        releaseName: v{{ .Version }}
        releaseRegex: \d+\.\d+\.\d+
        fileName: direnv.{{ .Platform }}-{{ .Arch }}
        overrides:
            darwin:
                amd64:
                    - darwin
                    - amd64
                    - ""
                arm64:
                    - darwin
                    - arm64
                    - ""
            linux:
                amd64:
                    - linux
                    - amd64
                    - ""
                arm64:
                    - linux
                    - arm64
                    - ""
        versionFlags:
            - --version
        versionRegex: \d+\.\d+\.\d+
    - name: fzf
      version: 0.45.0
      source:
        org: junegunn
        repo: fzf
        releaseName: '{{ .Version }}'
        releaseRegex: \d+\.\d+\.\d+
        fileName: fzf-{{ .Version }}-{{ .Platform }}_{{ .Arch }}.{{ .Ext }}
        overrides:
            darwin:
                amd64:
                    - darwin
                    - amd64
                    - zip
                arm64:
                    - darwin
                    - arm64
                    - zip
            linux:
                amd64:
                    - linux
                    - amd64
                    - tar.gz
                arm64:
                    - linux
                    - arm64
                    - tar.gz
        versionFlags:
            - --version
        versionRegex: \d+\.\d+\.\d+
    - name: starship
      version: 1.17.1
      source:
        org: starship
        repo: starship
        releaseName: v{{ .Version }}
        releaseRegex: \d+\.\d+\.\d+
        fileName: starship-{{ .Arch }}-{{ .Platform }}.{{ .Ext }}
        overrides:
            darwin:
                amd64:
                    - apple-darwin
                    - x86_64
                    - tar.gz
                arm64:
                    - apple-darwin
                    - aarch64
                    - tar.gz
            linux:
                amd64:
                    - unknown-linux-musl
                    - x86_64
                    - tar.gz
                arm64:
                    - unknown-linux-musl
                    - aarch64
                    - tar.gz
        versionFlags:
            - --version
        versionRegex: \d+\.\d+\.\d+
    - name: rg
      version: 14.1.0
      source:
        org: BurntSushi
        repo: ripgrep
        releaseName: '{{ .Version }}'
        releaseRegex: \d+\.\d+\.\d+
        fileName: ripgrep-{{ .Version }}-{{ .Arch }}-{{ .Platform }}.{{ .Ext }}
        overrides:
            darwin:
                amd64:
                    - apple-darwin
                    - x86_64
                    - tar.gz
                arm64:
                    - apple-darwin
                    - aarch64
                    - tar.gz
            linux:
                amd64:
                    - unknown-linux-musl
                    - x86_64
                    - tar.gz
                arm64:
                    - unknown-linux-gnu
                    - aarch64
                    - tar.gz
        versionFlags:
            - --version
        versionRegex: \d+\.\d+\.\d+
    - name: lefthook
      version: 1.5.6
      source:
        org: evilmartians
        repo: lefthook
        releaseName: v{{ .Version }}
        releaseRegex: \d+\.\d+\.\d+
        fileName: lefthook_{{ .Version }}_{{ .Platform }}_{{ .Arch }}.gz
        overrides:
            darwin:
                amd64:
                    - MacOS
                    - x86_64
                    - ""
                arm64:
                    - MacOS
                    - arm64
                    - ""
            linux:
                amd64:
                    - Linux
                    - x86_64
                    - ""
                arm64:
                    - Linux
                    - aarch64
                    - ""
        versionFlags:
            - version
        versionRegex: \d+\.\d+\.\d+
