binaries:
  - name: delta
    source: https://github.com/dandavison/delta/releases/download/{{ .Version }}/delta-{{ .Version }}-{{ .Arch }}-{{ .Platform }}.{{ .Ext }}
    version: "0.16.5"
    platforms:
      linux:
        amd64: [unknown-linux-gnu, x86_64, tar.gz]
        arm64: [unknown-linux-gnu, aarch64, tar.gz]
      darwin:
        amd64: [apple-darwin, x86_64, tar.gz]
        arm64: [apple-darwin, aarch64, tar.gz]
  - name: direnv
    source: https://github.com/direnv/direnv/releases/download/v{{ .Version }}/direnv.{{ .Platform }}-{{ .Arch }}
    version: "2.33.0"
    platforms:
      linux:
        amd64: [linux, amd64, ""]
        arm64: [linux, arm64, ""]
      darwin:
        amd64: [darwin, amd64, ""]
        arm64: [darwin, arm64, ""]
  - name: fzf
    source: https://github.com/junegunn/fzf/releases/download/{{ .Version }}/fzf-{{ .Version }}-{{ .Platform }}_{{ .Arch }}.{{ .Ext }}
    version: "0.45.0"
    platforms:
      linux:
        amd64: [linux, amd64, tar.gz]
        arm64: [linux, arm64, tar.gz]
      darwin:
        amd64: [darwin, amd64, zip]
        arm64: [darwin, arm64, zip]
  - name: starship
    source: https://github.com/starship/starship/releases/download/v{{ .Version }}/starship-{{ .Arch }}-{{ .Platform }}.{{ .Ext }}
    version: "1.17.0"
    platforms:
      linux:
        amd64: [unknown-linux-musl, x86_64, tar.gz]
        arm64: [unknown-linux-musl, aarch64, tar.gz]
      darwin:
        amd64: [apple-darwin, x86_64, tar.gz]
        arm64: [apple-darwin, aarch64, tar.gz]
  - name: rg
    source: https://github.com/BurntSushi/ripgrep/releases/download/{{ .Version }}/ripgrep-{{ .Version }}-{{ .Arch }}-{{ .Platform }}.{{ .Ext }}
    version: "14.0.3"
    platforms:
      linux:
        amd64: [unknown-linux-musl, x86_64, tar.gz]
        arm64: [unknown-linux-gnu, aarch64, tar.gz]
      darwin:
        amd64: [apple-darwin, x86_64, tar.gz]
        arm64: [apple-darwin, aarch64, tar.gz]
