apiVersion: garb.noizwaves.com/v1alpha1
kind: Package
metadata:
  name: rg
spec:
  gitHubRelease:
    org: BurntSushi
    repo: ripgrep
    name: "{{ .Version }}"
    versionRegex: \d+\.\d+\.\d+
    fileName:
      darwin,amd64: ripgrep-{{ .Version }}-x86_64-apple-darwin.tar.gz
      darwin,arm64: ripgrep-{{ .Version }}-aarch64-apple-darwin.tar.gz
      linux,amd64: ripgrep-{{ .Version }}-x86_64-unknown-linux-musl.tar.gz
      linux,arm64: ripgrep-{{ .Version }}-aarch64-unknown-linux-gnu.tar.gz
  program:
    versionArgs: [--version]
    versionRegex: \d+\.\d+\.\d+
