apiVersion: grab.noizwaves.com/v1alpha1
kind: Package
metadata:
  name: diffsitter
spec:
  gitHubRelease:
    org: afnanenayet
    repo: diffsitter
    name: "v{{ .Version }}"
    versionRegex: \d+\.\d+\.\d+
    fileName:
      darwin,amd64: diffsitter-x86_64-apple-darwin.tar.gz
      darwin,arm64: diffsitter-aarch64-apple-darwin.tar.gz
      linux,amd64: diffsitter-x86_64-unknown-linux-gnu.tar.gz
      linux,arm64: diffsitter-aarch64-unknown-linux-gnu.tar.gz
  program:
    versionArgs: [--version]
    versionRegex: \d+\.\d+\.\d+
