apiVersion: grab.noizwaves.com/v1alpha1
kind: Package
metadata:
  name: glow
spec:
  gitHubRelease:
    org: charmbracelet
    repo: glow
    name: v{{ .Version }}
    versionRegex: \d+\.\d+\.\d+
    fileName:
      darwin,amd64: glow_{{ .Version }}_Darwin_x86_64.tar.gz
      darwin,arm64: glow_{{ .Version }}_Darwin_arm64.tar.gz
      linux,amd64: glow_{{ .Version }}_Linux_x86_64.tar.gz
      linux,arm64: glow_{{ .Version }}_Linux_arm64.tar.gz
    embeddedBinaryPath:
      darwin,amd64: glow_{{ .Version }}_Darwin_x86_64/glow
      darwin,arm64: glow_{{ .Version }}_Darwin_arm64/glow
      linux,amd64: glow_{{ .Version }}_Linux_x86_64/glow
      linux,arm64: glow_{{ .Version }}_Linux_arm64/glow
  program:
    versionArgs: [--version]
    versionRegex: \d+\.\d+\.\d+
