apiVersion: grab.noizwaves.com/v1alpha1
kind: Package
metadata:
  name: scope-intercept
spec:
  gitHubRelease:
    org: ethankhall
    repo: scope
    name: "v{{ .Version }}"
    versionRegex: \d+\.\d+\.\d+
    fileName:
      darwin,amd64: dev-scope-x86_64-apple-darwin.tar.xz
      darwin,arm64: dev-scope-aarch64-apple-darwin.tar.xz
      linux,amd64: dev-scope-x86_64-unknown-linux-gnu.tar.xz
      linux,arm64: dev-scope-aarch64-unknown-linux-gnu.tar.xz
  program:
    versionArgs: [--version]
    versionRegex: \d+\.\d+\.\d+
