apiVersion: grab.noizwaves.com/v1alpha1
kind: Package
metadata:
  name: scope-intercept
spec:
  gitHubRelease:
    org: ethankhall
    repo: scope
    name: "{{ .Version }}"
    versionRegex: \d+\.\d+\.\d+
    fileName:
      darwin,amd64: scope-{{ .Version }}-darwin.tgz
      darwin,arm64: scope-{{ .Version }}-darwin.tgz
      linux,amd64: scope-{{ .Version }}-x86_64-unknown-linux-gnu.tgz
      linux,arm64: scope-{{ .Version }}-aarch64-unknown-linux-gnu.tgz
  program:
    versionArgs: [--version]
    versionRegex: \d+\.\d+\.\d+
