apiVersion: grab.noizwaves.com/v1alpha1
kind: Package
metadata:
  name: tv
spec:
  gitHubRelease:
    org: alexpasmantier
    repo: television
    name: '{{ .Version }}'
    versionRegex: \d+\.\d+\.\d+
    fileName:
      darwin,amd64: tv-{{ .Version }}-x86_64-apple-darwin.tar.gz
      darwin,arm64: tv-{{ .Version }}-aarch64-apple-darwin.tar.gz
      linux,amd64: tv-{{ .Version }}-x86_64-unknown-linux-gnu.deb
      linux,arm64: tv-{{ .Version }}-aarch64-unknown-linux-gnu.deb
    embeddedBinaryPath:
      darwin,amd64: tv-{{ .Version }}-x86_64-apple-darwin/tv
      darwin,arm64: tv-{{ .Version }}-aarch64-apple-darwin/tv
      linux,amd64: tv-{{ .Version }}-x86_64-unknown-linux-gnu/tv
      linux,arm64: tv-{{ .Version }}-aarch64-unknown-linux-gnu/tv
  program:
    versionArgs: [--version]
    versionRegex: \d+\.\d+\.\d+
