
notify = ["/Users/adam.neumann/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
model = "gpt-5.6-sol"
model_reasoning_effort = "xhigh"

[desktop]
dock-icon-preference = "codex-system"
followUpQueueMode = "queue"

[marketplaces.openai-bundled]
last_updated = "2026-08-31T13:45:53Z"
source_type = "local"
source = "/Users/adam.neumann/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-08-03T21:03:48Z"
source_type = "local"
source = "/Users/adam.neumann/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[features]
js_repl = false

[mcp_servers.node_repl]
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120.0

[mcp_servers.node_repl.env]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.727.51351"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"
CODEX_HOME = "/Users/adam.neumann/.codex"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "028a14b6eaa6d98dac2aae00764345ab9f244801ed8493d42b9af3be5575006e,f204d340535055781952b10ed396de20b842f00a19e430852f7e121ad1ce91f6"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/adam.neumann/.codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.slackgustoofficialmcp]
url = "https://gusto.runlayer.com/api/v1/proxy/1ceccfb7-3fea-4c7d-a82f-673dac326434/mcp"

[mcp_servers.githubgusto]
url = "https://gusto.runlayer.com/api/v1/proxy/79f29b16-6650-4529-91f8-2c94c00c641c/mcp"

[mcp_servers.buildkite]
url = "https://gusto.runlayer.com/api/v1/proxy/bb9748bc-72b7-43b8-a4b6-c201e9204017/mcp"

[projects."/Users/adam.neumann/Documents/New project"]
trust_level = "trusted"

[projects."/Users/adam.neumann/workspace/terraform"]
trust_level = "trusted"

[projects."/Users/adam.neumann/workspace/build-stability"]
trust_level = "trusted"

[projects."/Users/adam.neumann/workspace/zenpayroll"]
trust_level = "trusted"

[projects."/Users/adam.neumann/workspace/build-base"]
trust_level = "trusted"

[shell_environment_policy.set]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "028a14b6eaa6d98dac2aae00764345ab9f244801ed8493d42b9af3be5575006e,f204d340535055781952b10ed396de20b842f00a19e430852f7e121ad1ce91f6"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/adam.neumann/.codex"
